name: Build

on:
  pull_request:
    branches:
      - OSC-MIGRATION
    paths:
      - "**.go"
      - "Dockerfile"
      - ".trivyignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "!tests/**"
  push:
    branches: [ OSC-MIGRATION ]
    paths:
      - "**.go"
      - "Dockerfile"
      - ".trivyignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "!tests/**"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Docker Lint
      run: bash -c "make dockerlint"
    - name: Verify
      run: bash -c "make verify"
    - name: Test
      run: bash -c "make test"
    - name: Image
      run: bash -c "make build-image"
    - name: Trivy-Scan
      id: trivyscan
      run: bash -c "make trivy-scan"
    - name: Trivy-Ignore-Check
      run: bash -c "make trivy-ignore-check"
    - name: Upload Scan if errors
      if: ${{ failure() && github.event_name != 'pull_request' && steps.trivyscan.outcome == 'failure' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: './.trivyscan/report.sarif'
