name: Credential Checking

on:
  pull_request:
    branches:
    - OSC-MIGRATION
    - master

jobs:
  cred-scan:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Scan credentials
      uses: outscale-dev/cred-scan@main
      with:
        scan_path: "./"
